name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  plan-artifact:
    name: Terraform plan to file
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ vars.TF_PATH }}
    
    steps:
      - name: Terraform plan
        run: |
          terraform plan -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan.txt
