name: CD Pipeline

on:
  push
#     branches:
#       - main

jobs:
  plan-artifact:
    name: Terraform plan to file
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ vars.TF_PATH }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: |
          terraform init -backend=false
      
      - name: Terraform plan
        run: |
          terraform plan -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan.txt
