name: CI Pipeline

on:
  push:    
  pull_request:
    branches:
      - main


jobs:
  lint-validate:
    name: Lint and Validate Terraform
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Check formatting
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Init 
      - name: Terraform Init
        run: terraform init -backend=false

      # Validate syntax
      - name: Terraform Validate
        run: terraform validate

      # Install TFLint
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      # Run TFLint
      - name: Run TFLint
        run: tflint --init && tflint