name: CI Pipeline

on:
  push:    
  pull_request:
    branches:
      - main


jobs:
  lint-validate:
    name: Lint and Validate Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: |
          terraform init -backend=false
          terraform validate

      - name: Run TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init && tflint


  security-scan:
    name: Terraform Security Scan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./terraform
          framework: terraform
          check: >
            CKV_SECRET_2,
            CKV_SECRET_6,
            CKV_SECRET_13,
            CKV_SECRET_14,
            CKV_AWS_24,
            CKV_AWS_25,
            CKV_AWS_260,
            CKV_AWS_382,
            CKV_AWS_16,
            CKV_AWS_17,
            CKV_AWS_19,
            CKV_AWS_86,
            CKV_AWS_119
          soft_fail: false

  